In [35]:
import pandas as pd
import numpy as np

# Simulated messy hospital data
data = {
    'patient_id': [101, 102, 103, 102, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'Bob', 'Diana', None, 'Frank'],
    'age': [34, 28, 150, 28, 45, 62, 29],  # Note: 150 is impossible
    'blood_type': ['A+', 'O-', 'B+', 'O-', None, 'AB+', 'A-'],
    'ward': ['Cardiology', 'neurology', 'Cardiology', 'neurology', 'Oncology', 'Cardiology', 'neurology'],
    'admission_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-01-20', '2024-02-10', '2024-02-15', '2024-03-01'],
    'days_admitted': [5, 3, 8, 3, None, 12, 4]
}

df = pd.DataFrame(data)

In [ ]:
#### Run .info() — which columns have missing values? name,blood_type, days_admitted
#### Run .describe() — identify the outlier in the age column. 150
##### Use .isnull().sum() to count missing values per column.
##### Use .duplicated().sum() to count duplicate rows.

In [36]:
#healthcheck
#df.info()
#df.describe()
#df.isnull().sum()
df.duplicated(subset=['patient_id']).sum()

1

In [3]:
# Remove the duplicate row (keep the first occurrence).
# Fix the impossible age (150) — replace it with the column median.
# Standardise the ward column — all values should be title case ('Cardiology', not 'cardiology').
# Fill the missing blood_type with the string 'Unknown'.
# Fill missing days_admitted with the column median.

In [37]:
#clean the data
df

,patient_id,name,age,blood_type,ward,admission_date,days_admitted
0,101,Alice,34,A+,Cardiology,2024-01-15,5.0
1,102,Bob,28,O-,neurology,2024-01-20,3.0
2,103,Charlie,150,B+,Cardiology,2024-02-01,8.0
3,102,Bob,28,O-,neurology,2024-01-20,3.0
4,104,Diana,45,None,Oncology,2024-02-10,NaN
5,105,None,62,AB+,Cardiology,2024-02-15,12.0
6,106,Frank,29,A-,neurology,2024-03-01,4.0

In [38]:
df = df.drop_duplicates()
df

,patient_id,name,age,blood_type,ward,admission_date,days_admitted
0,101,Alice,34,A+,Cardiology,2024-01-15,5.0
1,102,Bob,28,O-,neurology,2024-01-20,3.0
2,103,Charlie,150,B+,Cardiology,2024-02-01,8.0
4,104,Diana,45,None,Oncology,2024-02-10,NaN
5,105,None,62,AB+,Cardiology,2024-02-15,12.0
6,106,Frank,29,A-,neurology,2024-03-01,4.0

In [40]:

median_age = df.loc[df['age']<120,'age'].median()
df.loc[df['age']>120,'age'] = median_age
df['ward']=df['ward'].str.title()
#df['ward']= df['ward'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 6
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      6 non-null      int64
 1   name            5 non-null      object
 2   age             6 non-null      float64
 3   blood_type      5 non-null      object
 4   ward            6 non-null      object
 5   admission_date  6 non-null      object
 6   days_admitted   5 non-null      float64
dtypes: float64(2), int64(1), object(4)
memory usage: 384.0+ bytes

/tmp/ipykernel_1838/3447850441.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ward']=df['ward'].str.title()

In [41]:
df

,patient_id,name,age,blood_type,ward,admission_date,days_admitted
0,101,Alice,34.0,A+,Cardiology,2024-01-15,5.0
1,102,Bob,28.0,O-,Neurology,2024-01-20,3.0
2,103,Charlie,39.5,B+,Cardiology,2024-02-01,8.0
4,104,Diana,45.0,None,Oncology,2024-02-10,NaN
5,105,None,62.0,AB+,Cardiology,2024-02-15,12.0
6,106,Frank,29.0,A-,Neurology,2024-03-01,4.0

In [ ]:
df
# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Fix impossible age
median_age = df.loc[df['age'] <= 120, 'age'].median()
df.loc[df['age'] > 120, 'age'] = median_age

# 3. Standardise ward names
df['ward'] = df['ward'].str.title()

# 4. Fill missing blood type
df['blood_type'] = df['blood_type'].fillna('Unknown')
# 5. Fill missing days admitted
df['days_admitted'] = df['days_admitted'].fillna(df['days_admitted'].median())

print(df)

,patient_id,name,age,blood_type,ward,admission_date,days_admitted
0,101,Alice,34.0,A+,Cardiology,2024-01-15,5.0
1,102,Bob,28.0,O-,Neurology,2024-01-20,3.0
2,103,Charlie,58.0,B+,Cardiology,2024-02-01,8.0
4,104,Diana,45.0,None,Oncology,2024-02-10,NaN
5,105,None,62.0,AB+,Cardiology,2024-02-15,12.0
6,106,Frank,29.0,A-,Neurology,2024-03-01,4.0

In [42]:
df['blood_type'] =df['blood_type'].fillna("Unknown")

/tmp/ipykernel_1838/3166157141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['blood_type'] =df['blood_type'].fillna("Unknown")

In [48]:
df['days_admitted'] =df['days_admitted'].fillna(df['days_admitted'].median())
df

/tmp/ipykernel_1838/2892236485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['days_admitted'] =df['days_admitted'].fillna(df['days_admitted'].median())

,patient_id,name,age,blood_type,ward,admission_date,days_admitted,risk_level
0,101,Alice,34.0,A+,Cardiology,2024-01-15,5.0,Low
1,102,Bob,28.0,O-,Neurology,2024-01-20,3.0,Low
2,103,Charlie,39.5,B+,Cardiology,2024-02-01,8.0,Low
4,104,Diana,45.0,Unknown,Oncology,2024-02-10,5.0,Medium
5,105,None,62.0,AB+,Cardiology,2024-02-15,12.0,High
6,106,Frank,29.0,A-,Neurology,2024-03-01,4.0,Low

In [49]:
df['admission_date']=pd.to_datetime(df['admission_date'])

def age_group(x):
    if x> 60:
        return "High"
    elif x<40:
        return "Low"
    else: 
        return "Medium"

df['risk_level'] =df['age'].apply(age_group)
df

/tmp/ipykernel_1838/426312356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['admission_date']=pd.to_datetime(df['admission_date'])
/tmp/ipykernel_1838/426312356.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['risk_level'] =df['age'].apply(age_group)

,patient_id,name,age,blood_type,ward,admission_date,days_admitted,risk_level
0,101,Alice,34.0,A+,Cardiology,2024-01-15,5.0,Low
1,102,Bob,28.0,O-,Neurology,2024-01-20,3.0,Low
2,103,Charlie,39.5,B+,Cardiology,2024-02-01,8.0,Low
4,104,Diana,45.0,Unknown,Oncology,2024-02-10,5.0,Medium
5,105,None,62.0,AB+,Cardiology,2024-02-15,12.0,High
6,106,Frank,29.0,A-,Neurology,2024-03-01,4.0,Low

In [54]:
df['ward'].value_counts()

Cardiology    3
Neurology     2
Oncology      1
Name: ward, dtype: int64

In [61]:
table = df.groupby('ward')['days_admitted'].mean().round(1).reset_index()
table

         ward  days_admitted
0  Cardiology            8.3
1   Neurology            3.5
2    Oncology            5.0